Hera features
fast-aircraft-design/FAST-OAD_CS25 pull request #36
Opened 2024-05-21 10:12 UTC by esnguyenvan

This PR allows the user to pilot the x-position of HTP and VTP, which was previously hard coded within the geometry component (fixing issue  #35)

The major modification concerns the position of the HTP in case of T-tail:
- Previously, it is was set at 100% of the fuselage length
- Now it is set relatively to the VTP tip chord

Additionally, the unit test of high-lift effect was fixed. Previously, it would give false positive all the time. This changed quite significantly the test value, but when checking the new test values with the first commit (3f5996b90b15703612dc6b31d4684531ef8975a0) everything is in coherence.

2024-06-10 06:17 UTC, ScottDelbecq requested changes
Thanks for this PR!
I have a few comments and suggestions.
Regarding `wet_area_coeff` I did not find the source for checking the correct value.
I think this PR is the opportunity to include global positions for VTP and HTP like for the wing: https://github.com/fast-aircraft-design/FAST-OAD_CS25/blob/main/src/fastoad_cs25/models/geometry/geom_components/wing/wing_global_positions.py

2024-06-13 15:37 UTC, christophe-david requested changes
Thanks for the update.

Small updates are needed for the HL polar test and computation of HTP area.

For the tail positions, I made several comments about horizontal tail. They also apply to vertical tail.

2024-06-18 11:59 UTC, ScottDelbecq commented on src/fastoad_cs25/models/geometry/geom_components/ht/compute_horizontal_tail.py
> +        )
I agree... :)
Corrected in 1c2dbfe0a9cc8ec1a5f8ad6f6ecd6d82141a99de and 5a24b251c7a5d4a9407bf67e3ab642c9c177c40b .

2024-06-18 12:48 UTC, ScottDelbecq commented on src/fastoad_cs25/models/geometry/geom_components/ht/components/compute_ht_local_positions.py
> +        x_tip = x_root + b_h / 2 * np.tan(sweep_25_ht / 180.0 * np.pi)
Corrected in b7170e01e4dfb27b6c1173097dfb95808cc50184

2024-06-18 19:05 UTC, ScottDelbecq commented on src/fastoad_cs25/models/handling_qualities/tail_sizing/compute_ht_area.py
> +                + vtp_span * np.tan(vtp_sweep_0)
Corrected in 78f2a30fb430b23dccb0321e08fbd1a668a09f42

2024-06-18 19:07 UTC, ScottDelbecq commented on src/fastoad_cs25/models/geometry/geom_components/ht/components/compute_ht_local_positions.py
> +        y_mac = b_h / 2 / 3 * (1 + 2 * taper_h) / (1 + taper_h)
Corrected in 78f2a30fb430b23dccb0321e08fbd1a668a09f42

2024-07-01 13:18 UTC, ScottDelbecq commented on src/fastoad_cs25/models/geometry/geom_components/ht/components/compute_ht_local_positions.py
> +        x_root = x_mac - y_mac * np.tan(sweep_25_ht / 180.0 * np.pi)
Corrected in [344d392](https://github.com/fast-aircraft-design/FAST-OAD_CS25/pull/36/commits/344d39271c4126069609a0b8c04490d9b442c468)

2024-07-01 13:33 UTC, ScottDelbecq commented on src/fastoad_cs25/models/handling_qualities/tail_sizing/compute_ht_area.py
> +            wet_area_coeff = 1.6  # TBD: these wet_area coefficients seem interverted
Corrected in [c21f15a](https://github.com/fast-aircraft-design/FAST-OAD_CS25/pull/36/commits/c21f15a1953a1e2938eb5fe677b07c0c0b2e0c1c)

2024-07-01 13:50 UTC, ScottDelbecq commented on src/fastoad_cs25/models/geometry/geom_components/ht/components/compute_ht_local_positions.py
> +        self.add_output("data:geometry:horizontal_tail:MAC:leading_edge:x:local", units="m")
Corrected in a5e4a91

2024-07-01 13:50 UTC, ScottDelbecq commented on src/fastoad_cs25/models/handling_qualities/tail_sizing/compute_ht_area.py
> +            wet_area_coeff = 2.0  # TBD: these wet_area coefficients seem interverted
I agree I did not change it but left a TODO in [c21f15a](https://github.com/fast-aircraft-design/FAST-OAD_CS25/pull/36/commits/c21f15a1953a1e2938eb5fe677b07c0c0b2e0c1c)

2024-07-02 13:32 UTC, christophe-david approved these changes
Ok for me. Thanks for the changes.

I suggest to wait for oncoming FAST-OAD-core v1.17.3 before merging. It will allow to check watchman tests on the branch.

Also, I still hesitate about keeping the variables `"data:geometry:vertical_tail:root:leading_edge:x:local"` and `"data:geometry:horizontal_tail:center:leading_edge:x:local"`, since their values are by definition 0. Yet it has the advantage of making clear the origin of the local reference frames, so it is maybe not so bad.

But if we decide to keep these variables, we should think about adding also `"data:geometry:wing:root:leading_edge:x:local"` for consistency.

2024-07-04 07:29 UTC, merged