Release 0.7.3
fast-aircraft-design/FAST-OAD_CS25 pull request #50
Opened 2024-11-06 06:52 UTC by ScottDelbecq

https://github.com/fast-aircraft-design/FAST-OAD_CS25/releases/tag/untagged-1dcca1a555921365cc22

2024-11-06 13:30 UTC, ScottDelbecq commented
> Your branch is not based on the HEAD of main, so it does not include #49 😅

Woops! Thanks I missed a failed fetch I guess!

2024-11-07 07:21 UTC, christophe-david requested changes
Some minor changes needed in the change log, and also, please rename the release as `v0.7.3`.

2024-11-07 07:21 UTC, christophe-david commented on CHANGELOG.rst
> +Version 0.7.23
```suggestion
Version 0.7.3
```

2024-11-07 07:21 UTC, christophe-david commented on CHANGELOG.rst
> +- Added scaling factors for tuning HTP and VTP areas (#49)
Just for sake of consistency, but honestly, I wouldn't have mentioned it if it had been the only point.
```suggestion
- Added scaling factors for tuning HTP and VTP areas. (#49)
```

2024-11-07 07:21 UTC, christophe-david commented on CHANGELOG.rst
> -
And well done for consistency 😃

2024-11-07 14:23 UTC, ScottDelbecq commented on CHANGELOG.rst
> -
haha thx

2024-11-08 08:40 UTC, christophe-david requested changes
Ok for the change log, but please, rename the [release](https://github.com/fast-aircraft-design/FAST-OAD_CS25/releases/tag/untagged-1dcca1a555921365cc22) as `v0.7.3`, consistently with previous releases.

2024-11-12 10:18 UTC, merged